docs: Cynthion documentation branch
greatscottgadgets/cynthion pull request #33
Opened 2024-01-18 08:04 UTC by antoinevg

This is the Cynthion documentation branch.

2024-06-27 22:01 UTC, mossmann requested changes
Great job! I'm very excited to get this cleaned up and merged. I think it is close, but I would like to see several changes. Perhaps the most important change is that the two photographs could be much smaller. I would rather not have giant images taking up room in the repo forever. Also, can the photographs be JPEGs instead of PNGs?

2024-06-28 09:53 UTC, antoinevg commented on docs/source/introduction.rst
> +- **LEDS A-E** - Five status LEDs managed by the debug micro-contoller.
Sticking with the convention for USB ports to match hardware exactly so it's just `A-E` and `0-5` -- doing same for PMOD's. Description text says that it's an LED.

2024-06-28 09:55 UTC, antoinevg commented on docs/source/introduction.rst
> +- **LEDS A-E** - Five status LEDs managed by the debug micro-contoller.
Fixed. Sphinx was being silly. It likes lots of whitespace between things.

2024-06-28 11:05 UTC, martinling commented on docs/source/hardware/bringup_guide.rst
> +If you choose to lock the bootloader, you should lock the first ``4KiB``
This should be 2KiB now, right?

2024-06-28 13:50 UTC, antoinevg commented on docs/source/hardware/bringup_guide.rst
> +If you choose to lock the bootloader, you should lock the first ``4KiB``
👍 updated!

2024-07-01 12:04 UTC, claui commented on docs/source/developer/soc_firmware_compilation.rst
> +    # change to the cynthion firmware directory
You probably want to capitalize this here?

```suggestion
    # change to the Cynthion firmware directory
```

2024-07-01 12:05 UTC, claui commented on docs/source/developer/soc_firmware_compilation.rst
> +    # change to the cynthion firmware directory
```suggestion
    # change to the Cynthion firmware directory
```

2024-07-01 12:05 UTC, claui commented on docs/source/developer/soc_firmware_compilation.rst
> +Once the firmware is running on the SoC you can execute some unittests to exercise the firmware.
```suggestion
Once the firmware is running on the SoC you can execute some unit tests to exercise the firmware.
```

2024-07-01 12:06 UTC, claui commented on docs/source/developer/soc_firmware_compilation.rst
> +    # change to the cynthion firmware directory
```suggestion
    # change to the Cynthion firmware directory
```

2024-07-01 12:24 UTC, claui commented on docs/source/developer/introduction.rst
> +To install the ``cynthion`` python package to allow for in-place editing of the sources you can use the ``pip --editable`` command:
```suggestion
To install the ``cynthion`` Python package to allow for in-place editing of the sources you can use the ``pip --editable`` command:
```

2024-07-01 12:25 UTC, claui commented on docs/source/developer/introduction.rst
> +    # install the cynthion python package, including dependencies required for gateware development
```suggestion
    # change to the `cynthion` Python package directory
    cd cynthion/python/

    # install the `cynthion` Python package, including dependencies required for gateware development
```

2024-07-01 13:58 UTC, antoinevg commented on docs/source/developer/bitstream_generation.rst
> +    # change to the cynthion python package directory
Backticking cynthion won't work in a code block, but you're on for a capital-P Python!

2024-07-01 14:05 UTC, antoinevg commented on docs/source/developer/introduction.rst
> +   `Amaranth HDL <https://github.com/amaranth-lang/amaranth>`__.
That shouldn't be in the list at all -- it's already a package dependency, tx!

2024-07-01 14:49 UTC, claui approved these changes
Looks great now!  
(Assuming you’re aware of the remaining `TODO` markers throughout the doc.)

2024-07-01 14:55 UTC, martinling approved these changes
Looks good to me. Obviously there's still things to add but everything here looks fine and we should go ahead and get it in.

2024-07-01 15:19 UTC, merged